-- AeroNex Complete Production Schema
create extension if not exists "uuid-ossp";

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  email text unique not null,
  name text not null,
  initials text,
  role text default 'passenger'
);

create table if not exists trips (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  passenger_ref text,
  inbound_flight text,
  outbound_flight text,
  origin text,
  connection_airport text,
  destination text,
  scheduled_connection_minutes numeric,
  buffer_minutes numeric,
  risk_band text,
  catch_probability numeric,
  source text default 'REFERENCE'
);

create table if not exists flight_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  flight_number text not null,
  airline text,
  origin text,
  destination text,
  event_type text not null, -- 'delay', 'gate_change', 'boarding', 'cancellation'
  event_data jsonb not null
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  model text not null,
  model_version text,
  flight_number text,
  features jsonb not null,
  prediction jsonb not null
);

create table if not exists connection_assessments (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  trip_id text,
  connection_airport text,
  buffer_minutes numeric,
  risk_band text,
  catch_probability numeric,
  top_factors jsonb,
  recommendation text
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  severity text,
  title text not null,
  message text not null,
  flight_number text,
  read boolean default false
);
