"""End-to-end smoke test on SYNTHETIC DATA.

The data below is generated by this test with a fixed seed, written only to a temporary folder, and used
ONLY to prove that the code runs end to end. Metrics from it mean nothing and are never shipped.
Run from ml/:  python -m unittest discover -s tests -v
"""
import importlib
import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
import numpy as np
import pandas as pd

ML = Path(__file__).resolve().parents[1]


def make_synthetic(path, seed=0):  # SYNTHETIC DATA
    rng = np.random.default_rng(seed)
    aps = ["DEL", "BOM", "BLR", "MAA", "HYD"]
    rows = []
    for day in pd.date_range("2024-01-01", periods=30):
        for i in range(260):
            o, d = rng.choice(aps, 2, replace=False)
            dep = int(rng.integers(5 * 60, 20 * 60))
            dur = int(rng.integers(90, 150))
            al = rng.choice(["6E", "AI"])
            rows.append({"Airline": al, "Flight Number": f"{al}{rng.integers(100, 999)}", "Origin": o, "Destination": d,
                         "Date": day.strftime("%d-%m-%Y"), "Scheduled Departure": f"{dep // 60:02d}:{dep % 60:02d}",
                         "Scheduled Arrival": f"{(dep + dur) // 60:02d}:{(dep + dur) % 60:02d}",
                         "Arrival Delay": float(np.round(rng.exponential(18) - 5))})
    df = pd.DataFrame(rows)
    df = pd.concat([df, df.iloc[:25]])  # deliberate exact duplicates to exercise cleaning
    df.to_csv(path, index=False)


class Smoke(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = Path(tempfile.mkdtemp())
        for sub in ("config", "data/reference", "data/raw", "data/processed", "data/features", "data/reports", "data/metadata", "models"):
            (cls.tmp / sub).mkdir(parents=True, exist_ok=True)
        shutil.copy(ML / "config/settings.yaml", cls.tmp / "config/settings.yaml")
        shutil.copy(ML / "data/reference/airport_profiles.csv", cls.tmp / "data/reference/airport_profiles.csv")
        make_synthetic(cls.tmp / "data/raw/synthetic.csv")
        (cls.tmp / "config/datasets.yaml").write_text(
            f"datasets:\n  synth:\n    enabled: true\n    source: local\n    path: {cls.tmp / 'data/raw/synthetic.csv'}\n    adapter: schedule\n"
            "    provenance: {source_name: SYNTHETIC DATA, source_url: n/a, license: n/a, official: false}\n"
            "  hf_unset:\n    enabled: true\n    source: huggingface\n    dataset_id: CONFIGURE_ME\n    adapter: huggingface\n")
        os.environ["AERONEX_ML_ROOT"] = str(cls.tmp)
        for m in [k for k in sys.modules if k == "src" or k.startswith("src.")]:
            del sys.modules[m]
        sys.path.insert(0, str(ML))
        cls.pipeline = importlib.import_module("src.pipeline")
        cls.train = importlib.import_module("src.train")
        cls.predictor = importlib.import_module("src.predictor")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmp, ignore_errors=True)
        os.environ.pop("AERONEX_ML_ROOT", None)

    def test_1_pipeline_and_cleaning(self):
        self.assertEqual(self.pipeline.main(), 0)
        rep = json.loads((self.tmp / "data/reports/cleaning_report.json").read_text())
        self.assertEqual(rep["duplicates"]["removed"], 25)
        self.assertEqual(rep["rows_before"] - rep["rows_after"], rep["removed_rows"])
        removed = pd.read_csv(self.tmp / "data/processed/removed_rows.csv")
        self.assertEqual(len(removed), rep["removed_rows"])  # nothing discarded silently
        build = json.loads((self.tmp / "data/reports/build_report.json").read_text())
        self.assertIn("DATA SOURCE UNAVAILABLE", build["sources"]["hf_unset"])
        conn = pd.read_csv(self.tmp / "data/features/connection_features.csv")
        self.assertTrue(conn["connection_time_min"].between(30, 360).all())
        for c in ("gate_change", "weather_risk"):
            self.assertTrue(conn[c].isna().all(), f"{c} must stay NaN when no real data exists (never randomised)")
        reg = json.loads((self.tmp / "data/metadata/dataset_registry.json").read_text())
        self.assertEqual(reg["datasets"][0]["record_count"], 7825)

    def test_2_train_and_predict(self):
        self.assertEqual(self.train.main(["--stage", "all"]), 0)
        meta = json.loads((self.tmp / "models/model_metadata.json").read_text())
        self.assertEqual(meta["split"]["split_method"], "temporal")
        self.assertEqual(meta["label_status"], "DERIVED PROTOTYPE LABEL")
        self.assertTrue(meta["warnings"], "leakage warning must be present for the deterministic label")
        self.assertTrue((self.tmp / "data/reports/model_comparison.csv").exists())
        p = self.predictor.Predictor()
        out = p.predict({"arrival_delay_min": 25, "connection_time_min": 65, "gate_walk_min": 12, "security_time_min": 8,
                         "immigration_time_min": 10, "boarding_cutoff_min": 20, "gate_change": 1, "terminal_change": 0,
                         "weather_risk": 0.2, "airport_congestion": 0.6})
        self.assertGreaterEqual(out["probability"], 0.5)           # buffer = 40 - 10-8-12-10-20 < 0
        self.assertIn(out["risk"], {"HIGH", "CRITICAL"})
        easy = p.predict({"arrival_delay_min": 0, "connection_time_min": 180, "connection_airport": "MAA"})
        self.assertLess(easy["probability"], 0.2)
        self.assertEqual(easy["risk"], "LOW")
        self.assertIn("gate_walk_min", easy["data_quality"]["from_airport_profile_estimated"])

    def test_3_untrained_state(self):
        for f in (self.tmp / "models").glob("*"):
            f.unlink()
        p = self.predictor.Predictor()
        self.assertEqual(p.health()["status"], "MODEL NOT TRAINED")
        with self.assertRaises(self.predictor.ModelNotTrained):
            p.predict({"connection_time_min": 90})


if __name__ == "__main__":
    unittest.main()
